In [2]:
import pandas as pd
import numpy as np
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

# Z-test

In [3]:
df = pd.read_csv('passport.csv')
df.head()

   processing_time
0             16.0
1             16.0
2             30.0
3             37.0
4             25.0

In [9]:
mu = 30
std = 12.5
alpha = 0.05

In [7]:
sample_mean = df['processing_time'].mean()

n = len(df)

In [10]:
z_stat = (sample_mean - mu) / (std/np.sqrt(n))

In [12]:
p_value = 2 * (1 - stats.norm.cdf(abs(z_stat)))

In [14]:
print("Sample Mean:", sample_mean)
print("Z statistics:", z_stat)
print("P value:", p_value)

Sample Mean: 27.05
Z statistics: -1.4925950555994747
P value: 0.13554321839923023

In [16]:
if p_value < alpha:
    print("Null hypothesis is rejected.")
    print("Claim is not supported.")
else:
    print("Failed to accept the null hypothesis.")
    print("Clainm is supported.")

Failed to accept the null hypothesis.
Clainm is supported.

# Onesample t_test

In [17]:
df = pd.read_csv('bollywoodmovies.csv')
df.head()

   production_cost
0              601
1              627
2              330
3              364
4              562

In [18]:
mu = 500
alpha = 0.05

In [20]:
t_stat, p_value = stats.ttest_1samp(df['production_cost'], mu)

print(t_stat)
print(p_value)

-2.2845532872667547
0.027862556406761777

In [21]:
if p_value < alpha:
    print("Reject the null hypothesis.")
    print("The belief about the average production cost is not correct.")
else:
    print("Fail to reject the null hypothesis.")
    print("The belief about average production cost is correct.")

Reject the null hypothesis.
The belief about the average production cost is not correct.

# Two sample t_test

In [22]:
df = pd.read_csv('healthdrink.csv')
df.head()

   height_increase_sheet1  height_increase_sheet2
0                     5.3                     8.6
1                     9.0                     5.8
2                     5.7                    10.2
3                     5.5                     8.5
4                     5.4                     6.8

In [23]:
drink = [5.3, 9.0,5.7, 5.5, 5.4]
no_drink =[8.6,5.8, 10.2, 8.5, 6.8]

In [24]:
t_stat, p_value = stats.ttest_ind(drink, no_drink)

print(t_stat, p_value)

-1.7258298562646328 0.1226558740358714

In [25]:
alpha = 0.05

if p_value <= alpha:
    print("Reject the null hypothesis.")
else:
    print("Fail to reject the null hypothesis.")

Fail to reject the null hypothesis.

# Paired t_test

In [26]:
df = pd.read_csv('breakups.csv')
df.head()

   Before_Breakup  After_Breakup
0             470            408
1             354            439
2             496            321
3             351            437
4             349            335

In [27]:
t_stat, p_value = stats.ttest_rel(df['Before_Breakup'], df['After_Breakup'])

print(t_stat, p_value)

-0.5375404241815106 0.5971346738292477

In [28]:
alpha = 0.05

if p_value <=alpha:
    print("Reject Null Hypothesis")
    print("Alcohol consumption changed after breakup")
else:
    print("Fail to Reject Null Hypothesis")
    print("No significance change in alcohol consumption")

Fail to Reject Null Hypothesis
No significance change in alcohol consumption

# Anova test

In [30]:
df = pd.read_csv('onestop.csv')
df.head()

   discount_0  discount_10  discount_20
0          39           34           42
1          32           41           43
2          25           45           44
3          25           39           46
4          37           38           41

In [31]:
sales_0 = df['discount_0']
sales_1 = df['discount_10']
sales_2 = df['discount_20']

In [33]:
f_stat, p_value = stats.f_oneway(sales_0, sales_1, sales_2)

print(f_stat, p_value)

65.86986401283694 3.82150066972564e-18

In [34]:
alpha = 0.05

if p_value < alpha:
    print("Discount has a significant impact on average sales quantity.")
else:
    print("Discount does not have a significant impact on average sales quantity.")

Discount has a significant impact on average sales quantity.

# Chisquare test

In [35]:
observed = [190, 185, 90, 35]
expected = [175, 200, 100, 25]

In [37]:
chi_stat, p_value = stats.chisquare(f_obs = observed, f_exp = expected)

print(chi_stat, p_value)

7.410714285714286 0.05989751420084909

In [38]:
alpha = 0.05

if p_value < alpha:
    print("Reject Null hypothesis.")
    print("Captain Cook's belief is not true.")
else:
    print("Fail to reject Null Hypothesis.")
    print("Captain cook's belief is true.")

Fail to reject Null Hypothesis.
Captain cook's belief is true.

# Model Building

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder

In [41]:
df = pd.read_csv(r"C:\Users\namit\OneDrive\Documents\CDAC ASSIGMENTS\MODULE 4 BDT\Data Files\titanic_clean .xls")
df.head()

,Unnamed: 0,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest,has_cabin_number
0,1,1.0,1.0,"Allen, Miss. Elisabeth Walton",female,29.0000,0.0,0.0,24160,211.3375,B5,S,2,NaN,"St Louis, MO",1
1,2,1.0,1.0,"Allison, Master. Hudson Trevor",male,0.9167,1.0,2.0,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON",1
2,3,1.0,0.0,"Allison, Miss. Helen Loraine",female,2.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1
3,4,1.0,0.0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON",1
4,5,1.0,0.0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1.0,2.0,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON",1

In [42]:
df.columns

Index(['Unnamed: 0', 'pclass', 'survived', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body',
       'home.dest', 'has_cabin_number'],
      dtype='object')

In [43]:
df.dtypes

Unnamed: 0            int64
pclass              float64
survived            float64
name                 object
sex                  object
age                 float64
sibsp               float64
parch               float64
ticket               object
fare                float64
cabin                object
embarked             object
boat                 object
body                float64
home.dest            object
has_cabin_number      int64
dtype: object

In [44]:
df.isnull().sum()

Unnamed: 0             0
pclass                 1
survived               1
name                   1
sex                    1
age                    0
sibsp                  1
parch                  1
ticket                 1
fare                   2
cabin               1015
embarked               0
boat                 824
body                1189
home.dest            565
has_cabin_number       0
dtype: int64

In [46]:
df.drop(columns =['Unnamed: 0', 'name', 'cabin', 'boat', 'body', 'home.dest'], inplace = True, errors = 'ignore')

In [49]:
df = df.dropna(subset = ['survived'])

In [51]:
df['pclass'].fillna(df['pclass'].mean(), inplace =True)
df['fare'].fillna(df['fare'].mean(), inplace =True)

C:\Users\namit\AppData\Local\Temp\ipykernel_9168\2871384708.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['pclass'].fillna(df['pclass'].mean(), inplace =True)
C:\Users\namit\AppData\Local\Temp\ipykernel_9168\2871384708.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['fare'].fillna(df['fare'].mean(), inplace =True)

In [52]:
labelencoder = LabelEncoder()

df['sex'] = labelencoder.fit_transform(df['sex'])
df['embarked'] = labelencoder.fit_transform(df['embarked'])

In [53]:
features = ['pclass', 'fare', 'sex', 'age']
target = 'survived'

In [54]:
X = df[features]
y = df[target]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =0.3, random_state = 42, stratify =y)

In [61]:
model = LogisticRegression(max_iter = 1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [62]:
y_pred = model.predict(X_test)

In [63]:
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(accuracy)
print(cm)

0.8040712468193384
[[208  35]
 [ 42 108]]

# Decision Tree

In [66]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(criterion = 'gini', max_depth=5)
model.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=5)

# Naive Bayes

In [ ]:
df = load_breast_cancer()

X = df.data
y = data.target
feature_names = data.feature_names
target_names = data.target_names

print("Number of samples:", X.shape[0])
print("Number of features:", X.shape[1])
print("Classes:", target_names)

In [ ]:
df = pd.DataFrame(X, columns=feature_names)
df['target'] = y
df.head()

In [ ]:
df.groupby('target')['mean radius'].mean()

In [ ]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(X_train, y_train)

In [ ]:
import pickle

with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

In [ ]:
model1 = pickle.load(open('model.pkl', 'rb'))

In [ ]:
#can import in the form of file also
X_new = [
    15.0, 20.0, 100.0, 800.0, 0.1, 0.2, 0.3, 0.1, 0.2, 0.1,
    0.3, 1.0, 2.0, 30.0, 0.005, 0.02, 0.03, 0.01, 0.02, 0.005,
    20.0, 25.0, 120.0, 1000.0, 0.15, 0.25, 0.35, 0.15, 0.25, 0.05
]

In [ ]:
target_names=['malignant', 'benign']

predicted_class= model1.predict([X_new])
print("\nPredicted class:", target_names[predicted_class])

# For other data

In [ ]:
X_new = [10, 200, 70, 25, 78, 28, 2.2, 30]
X_new_df = pd.DataFrame([X_new], columns = X_train.columns)

target = [0, 1]
predic_class = model1.predict(X_new_df)
print("Predicted class:", target[predic_class[0]])

# Univariate/ bivariate analysis

In [67]:
import warnings
warnings.filterwarnings('ignore')

In [69]:
df = pd.read_csv('synthetic_data_300.csv')
df.head()

      Name          City  Score1  Score2
0     Drew      New York    6.43   23.68
1  Emerson      San Jose   68.24    1.02
2    Riley       Phoenix   96.93   98.74
3   Finley  Philadelphia   75.16   26.27
4   Morgan      New York   32.31   25.48

In [70]:
IQ1 = df['Score1'].quantile(.25)
IQ3 = df['Score1'].quantile(.75)
IQR = IQ3 - IQ1

lowerboundary = IQ1 - (1.5*IQR)
upperboundary = IQ3 + (1.5*IQR)

display(IQ1, IQ3, IQR, lowerboundary, upperboundary)

np.float64(24.9825)

np.float64(74.2925)

np.float64(49.31)

np.float64(-48.9825)

np.float64(148.2575)

In [71]:
outliers = df[(df['Score1'] < lowerboundary) | (df['Score1'] > upperboundary)]
outliers

Empty DataFrame
Columns: [Name, City, Score1, Score2]
Index: []

In [72]:
df_clean = df[(df['Score1']>= lowerboundary) & (df['Score1'] <= upperboundary)]
df_clean

        Name          City  Score1  Score2
0       Drew      New York    6.43   23.68
1    Emerson      San Jose   68.24    1.02
2      Riley       Phoenix   96.93   98.74
3     Finley  Philadelphia   75.16   26.27
4     Morgan      New York   32.31   25.48
..       ...           ...     ...     ...
295   Jordan       Chicago   71.15    0.15
296    Avery   San Antonio   15.75   94.78
297    Jamie  Philadelphia   10.62    3.77
298   Elliot        Dallas   76.21   74.12
299     Alex     San Diego   80.82   50.18

[300 rows x 4 columns]

#**Corr/Cov**

In [75]:
corr = df['Score1'].corr(df['Score2'])
print(corr)

co_matrix = df[['Score1', 'Score2']].corr()
print(co_matrix)

-0.033790730619900684
          Score1    Score2
Score1  1.000000 -0.033791
Score2 -0.033791  1.000000

In [81]:
df['Score1'].mean()
df['Name'].mode()
df['Score2'].median()

np.float64(50.43)

In [82]:
df.groupby('City')['Score1'].mean()

City
Chicago         48.380909
Dallas          45.460000
Houston         51.640909
Los Angeles     48.722500
New York        53.780323
Philadelphia    43.398065
Phoenix         52.087812
San Antonio     44.997857
San Diego       57.656774
San Jose        52.986667
Name: Score1, dtype: float64

# Visual Analysis

In [84]:
import seaborn as sn
import matplotlib.pyplot as plt

#**Univariate**

In [ ]:
sn.boxplot(df['Score1'])

In [ ]:
plt.boxplot(df['Score1'])
plt.title("Boxplot for Score1")
plt.ylabel("Score1")
plt.show()

In [ ]:
plt.hist(df['Score2'], bins = 20)
plt.xlabel('Scores')
plt.ylabel("Frequency")
plt.title("Distribution of Scores")
plt.show()

#**Bivariate**

In [ ]:
plt.scatter(df['Score1'], df['Score2'])
plt.xlabel("Score1")
plt.ylabel("Score2")
plt.show()

In [ ]:
ct = pd.crosstab(df['Name'], df['City'])
sn.heatmap(ct, annot = True)
plt.title("HeatMap")

In [ ]:
sn.heatmap(df.corr(), annot = True)
plt.title("Correlation Heatmap")
plt.show()

# Binom/Poisson

In [95]:
from scipy.stats import binom
from scipy.stats import poisson

In [96]:
n = 10
p= 0.08

In [101]:
p_all= binom.pmf(10, n, p)
print(p_all)

1.0737418240000001e-11

In [103]:
p_2 = binom.pmf(2, n, p)
print(p_2)

0.14780703546361773

In [104]:
p_0 = binom.pmf(0, n, p)
print(p_0)

0.4343884542236322

In [105]:
p_a2 = 1 - binom.cdf(1, n, p)
print(p_a2)

0.18788245514712265

In [107]:
lam = 10
#p(X<=5)
prob1 = poisson.cdf(5, lam)
print(prob1)

0.06708596287903189

In [108]:
#p(x>30)

prob2 =1- poisson.cdf(30, lam)
print(prob2)

7.983794658716903e-08

# Qualitative Analysis

In [110]:
df = pd.read_csv('BEML.csv')
df.head()

,Date,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
0,2010-01-04,1121.0,1151.00,1121.00,1134.0,1135.60,101651.0,1157.18
1,2010-01-05,1146.8,1149.00,1128.75,1135.0,1134.60,59504.0,676.47
2,2010-01-06,1140.0,1164.25,1130.05,1137.0,1139.60,128908.0,1482.84
3,2010-01-07,1142.0,1159.40,1119.20,1141.0,1144.15,117871.0,1352.98
4,2010-01-08,1156.0,1172.00,1140.00,1141.2,1144.05,170063.0,1971.42

In [112]:
df.mean(numeric_only=True)

Open                       700.233180
High                       713.384704
Low                        686.280276
Last                       698.413370
Close                      698.435221
Total Trade Quantity    235230.935020
Turnover (Lacs)           1682.773985
dtype: float64

In [113]:
df['Close'].mean()

np.float64(698.4352213916044)

In [115]:
df.median(numeric_only = True)

Open                       685.00
High                       699.80
Low                        666.75
Last                       683.00
Close                      682.15
Total Trade Quantity    128205.00
Turnover (Lacs)            678.09
dtype: float64

In [116]:
df['Close'].median()

np.float64(682.15)

In [117]:
df.mode()

,Date,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
0,2010-01-04,1000.0,1018.0,271.0,530.0,529.75,61830.0,58.59
1,2010-01-05,1009.0,NaN,NaN,1022.0,660.70,80586.0,90.35
2,2010-01-06,NaN,NaN,NaN,1132.0,873.00,84927.0,102.11
3,2010-01-07,NaN,NaN,NaN,NaN,887.70,99062.0,119.25
4,2010-01-08,NaN,NaN,NaN,NaN,NaN,NaN,136.41
...,...,...,...,...,...,...,...,...
1734,2016-12-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1735,2016-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1736,2016-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1737,2016-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1738,2016-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [118]:
df['Close'].mode()

0    529.75
1    660.70
2    873.00
3    887.70
Name: Close, dtype: float64

In [119]:
df.var(numeric_only=True)

Open                    1.286356e+05
High                    1.326162e+05
Low                     1.235905e+05
Last                    1.277052e+05
Close                   1.277561e+05
Total Trade Quantity    1.268153e+11
Turnover (Lacs)         7.319353e+06
dtype: float64

In [120]:
df['Close'].var()

np.float64(127756.11184130597)

In [121]:
df.std(numeric_only=True)

Open                       358.658024
High                       364.165083
Low                        351.554420
Last                       357.358712
Close                      357.429870
Total Trade Quantity    356111.351618
Turnover (Lacs)           2705.430289
dtype: float64

In [122]:
df['Close'].std()

np.float64(357.42986982246737)

In [123]:
df.quantile([0.25, 0.50, 0.75], numeric_only=True)

,Open,High,Low,Last,Close,Total Trade Quantity,Turnover (Lacs)
0.25,371.025,379.3,367.525,370.55,370.65,58781.5,263.16
0.50,685.000,699.8,666.750,683.00,682.15,128205.0,678.09
0.75,1012.000,1027.8,997.000,1011.20,1010.55,251344.0,1956.53

# ASS 1&2

In [ ]:
df.iloc[:,[0,5,1]]
new_df = df.loc[:,['Date','Close','Open']]

new_df['gain'] = new_df['Close'].diff()
new_df = new_df.dropna()
#create new file
new_df.to_csv("BemlNew_Data.csv", index=False)

In [ ]:
#c) Display the first five observations with only two columns
df[['Date', 'Open']].head()

In [ ]:
#f) Convert time attribute to index
new_df['Date'] = pd.to_datetime(new_df['Date'])
new_df.set_index('Date', inplace = True)
print(new_df)

#h) Display the normal distribution plot of close attribute
plt.figure(figsize=(8,5))
sns.histplot(new_df['Close'], kde = True)
plt.title("Normal Distribution of Close Price")
plt.xlabel("Close Price")
plt.ylabel("Frequency")
plt.show()

# Factor

In [ ]:
!pip install factor_analyzer
from factor_analyzer import FactorAnalyzer
import matplotlib.pyplot as plt
from sklearn.decomposition import FactorAnalysis
from sklearn.preprocessing import StandardScaler

In [ ]:
traits_cols = [col for col in df.columns if col in
               ['A1', 'A2', 'A3', 'A4', 'A5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'E1', 'E2', 'E3', 'E4', 'E5', 'N1', 'N2', 'N3', 'N4', 'N5', 'O1', 'O2',
       'O3', 'O4', 'O5']
              ]
df = df[traits_cols]
df.head()

df.isnull().sum()
#Replacing it by mean
df = df.fillna(df.mean())

In [ ]:
from sklearn.preprocessing import StandardScaler

X = df.apply(pd.to_numeric, errors='coerce').dropna()
X_scaled = StandardScaler().fit_transform(X)

In [ ]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all, kmo_model = calculate_kmo(X_scaled)
kmo_model

In [ ]:
from factor_analyzer import FactorAnalyzer
import matplotlib.pyplot as plt

fa = FactorAnalyzer()
fa.fit(X_scaled)
ev, v = fa.get_eigenvalues()

plt.scatter(range(1, X_scaled.shape[1] + 1), ev)
plt.plot(range(1, X_scaled.shape[1] + 1), ev)
plt.title('Scree Plot')
plt.xlabel('Fcators')
plt.ylabel('Eigenvalue')
plt.grid()
plt.show()

In [ ]:
fa = FactorAnalyzer(n_factors=5, rotation=None)
fa.fit(X_scaled)
loadings = fa.loadings_
loadings

In [124]:
loadings_df = pd.DataFrame(loadings, index=df.columns, columns=['Factor1', 'Factor2', 'Factor3', 'Factor4', 'Fcator5'])
loadings_df

NameError: name 'loadings' is not defined

In [ ]:
#performing factor loading with rotation(orthogonal)

fa = FactorAnalyzer(n_factors=5, rotation='varimax')
fa.fit(X_scaled)
loadings = fa.loadings_
loadings